### ISSUE TITLE
kind in compute_Hc

### ISSUE THREAD

**Issue by zhcong** [Mottl/hurst#3]
I have a cycle data, how I choose the "random_walk","change" and "price"? My data looks like Sin function.

**Comment by Mottl** [comment]
The `kind` parameter can have the following values:
`'change'`: a series is just random values (i.e. `np.random.randn(...)`)
`'random_walk'`: a series is a cumulative sum of changes (i.e.`np.cumsum(np.random.randn(...)`)
`'price'`: a series is a cumulative product of changes (i.e.`np.cumprod(1+epsilon*np.random.randn(...)`)

For `sin` you should use `'random_walk'`.

**Comment by zhcong** [comment]
Thanks!

**Comment by zhcong** [comment]
Hi, I extract 100 items in my data, and H > 0.5. But calculate the  H < 0.5 with all my data. My data have 8000 items, It that ok? Thanks.
